// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountName holds the string denoting the accountname field in the database.
	FieldAccountName = "account_name"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldSub holds the string denoting the sub field in the database.
	FieldSub = "sub"
	// FieldNameJa holds the string denoting the nameja field in the database.
	FieldNameJa = "name_ja"
	// FieldGivenName holds the string denoting the givenname field in the database.
	FieldGivenName = "given_name"
	// FieldFamilyName holds the string denoting the familyname field in the database.
	FieldFamilyName = "family_name"
	// FieldLocale holds the string denoting the locale field in the database.
	FieldLocale = "locale"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldAccountName,
	FieldPassword,
	FieldSub,
	FieldNameJa,
	FieldGivenName,
	FieldFamilyName,
	FieldLocale,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AccountNameValidator is a validator for the "AccountName" field. It is called by the builders before save.
	AccountNameValidator func(string) error
	// PasswordValidator is a validator for the "Password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// SubValidator is a validator for the "Sub" field. It is called by the builders before save.
	SubValidator func(string) error
	// NameJaValidator is a validator for the "NameJa" field. It is called by the builders before save.
	NameJaValidator func(string) error
	// GivenNameValidator is a validator for the "GivenName" field. It is called by the builders before save.
	GivenNameValidator func(string) error
	// FamilyNameValidator is a validator for the "FamilyName" field. It is called by the builders before save.
	FamilyNameValidator func(string) error
	// LocaleValidator is a validator for the "Locale" field. It is called by the builders before save.
	LocaleValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountName orders the results by the AccountName field.
func ByAccountName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountName, opts...).ToFunc()
}

// ByPassword orders the results by the Password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// BySub orders the results by the Sub field.
func BySub(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSub, opts...).ToFunc()
}

// ByNameJa orders the results by the NameJa field.
func ByNameJa(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameJa, opts...).ToFunc()
}

// ByGivenName orders the results by the GivenName field.
func ByGivenName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGivenName, opts...).ToFunc()
}

// ByFamilyName orders the results by the FamilyName field.
func ByFamilyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFamilyName, opts...).ToFunc()
}

// ByLocale orders the results by the Locale field.
func ByLocale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocale, opts...).ToFunc()
}
