// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_name", Type: field.TypeString, Unique: true, Size: 256},
		{Name: "password", Type: field.TypeString, Size: 256},
		{Name: "sub", Type: field.TypeString, Size: 256},
		{Name: "name_ja", Type: field.TypeString, Size: 256},
		{Name: "given_name", Type: field.TypeString, Size: 256},
		{Name: "family_name", Type: field.TypeString, Size: 256},
		{Name: "locale", Type: field.TypeString, Size: 2},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
