// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/dev-shimada/oidc-prac/authorization/ent/schema"
	"github.com/dev-shimada/oidc-prac/authorization/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAccountName is the schema descriptor for AccountName field.
	userDescAccountName := userFields[1].Descriptor()
	// user.AccountNameValidator is a validator for the "AccountName" field. It is called by the builders before save.
	user.AccountNameValidator = func() func(string) error {
		validators := userDescAccountName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_AccountName string) error {
			for _, fn := range fns {
				if err := fn(_AccountName); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for Password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "Password" field. It is called by the builders before save.
	user.PasswordValidator = func() func(string) error {
		validators := userDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_Password string) error {
			for _, fn := range fns {
				if err := fn(_Password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescSub is the schema descriptor for Sub field.
	userDescSub := userFields[3].Descriptor()
	// user.SubValidator is a validator for the "Sub" field. It is called by the builders before save.
	user.SubValidator = func() func(string) error {
		validators := userDescSub.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_Sub string) error {
			for _, fn := range fns {
				if err := fn(_Sub); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescNameJa is the schema descriptor for NameJa field.
	userDescNameJa := userFields[4].Descriptor()
	// user.NameJaValidator is a validator for the "NameJa" field. It is called by the builders before save.
	user.NameJaValidator = func() func(string) error {
		validators := userDescNameJa.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_NameJa string) error {
			for _, fn := range fns {
				if err := fn(_NameJa); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescGivenName is the schema descriptor for GivenName field.
	userDescGivenName := userFields[5].Descriptor()
	// user.GivenNameValidator is a validator for the "GivenName" field. It is called by the builders before save.
	user.GivenNameValidator = func() func(string) error {
		validators := userDescGivenName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_GivenName string) error {
			for _, fn := range fns {
				if err := fn(_GivenName); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescFamilyName is the schema descriptor for FamilyName field.
	userDescFamilyName := userFields[6].Descriptor()
	// user.FamilyNameValidator is a validator for the "FamilyName" field. It is called by the builders before save.
	user.FamilyNameValidator = func() func(string) error {
		validators := userDescFamilyName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_FamilyName string) error {
			for _, fn := range fns {
				if err := fn(_FamilyName); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescLocale is the schema descriptor for Locale field.
	userDescLocale := userFields[7].Descriptor()
	// user.LocaleValidator is a validator for the "Locale" field. It is called by the builders before save.
	user.LocaleValidator = func() func(string) error {
		validators := userDescLocale.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_Locale string) error {
			for _, fn := range fns {
				if err := fn(_Locale); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
}
