// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-shimada/oidc-prac/authorization/ent/predicate"
	"github.com/dev-shimada/oidc-prac/authorization/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPassword sets the "Password" field.
func (_u *UserUpdate) SetPassword(v string) *UserUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "Password" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetSub sets the "Sub" field.
func (_u *UserUpdate) SetSub(v string) *UserUpdate {
	_u.mutation.SetSub(v)
	return _u
}

// SetNillableSub sets the "Sub" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSub(v *string) *UserUpdate {
	if v != nil {
		_u.SetSub(*v)
	}
	return _u
}

// SetNameJa sets the "NameJa" field.
func (_u *UserUpdate) SetNameJa(v string) *UserUpdate {
	_u.mutation.SetNameJa(v)
	return _u
}

// SetNillableNameJa sets the "NameJa" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNameJa(v *string) *UserUpdate {
	if v != nil {
		_u.SetNameJa(*v)
	}
	return _u
}

// SetGivenName sets the "GivenName" field.
func (_u *UserUpdate) SetGivenName(v string) *UserUpdate {
	_u.mutation.SetGivenName(v)
	return _u
}

// SetNillableGivenName sets the "GivenName" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGivenName(v *string) *UserUpdate {
	if v != nil {
		_u.SetGivenName(*v)
	}
	return _u
}

// SetFamilyName sets the "FamilyName" field.
func (_u *UserUpdate) SetFamilyName(v string) *UserUpdate {
	_u.mutation.SetFamilyName(v)
	return _u
}

// SetNillableFamilyName sets the "FamilyName" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFamilyName(v *string) *UserUpdate {
	if v != nil {
		_u.SetFamilyName(*v)
	}
	return _u
}

// SetLocale sets the "Locale" field.
func (_u *UserUpdate) SetLocale(v string) *UserUpdate {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "Locale" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLocale(v *string) *UserUpdate {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "Password", err: fmt.Errorf(`ent: validator failed for field "User.Password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sub(); ok {
		if err := user.SubValidator(v); err != nil {
			return &ValidationError{Name: "Sub", err: fmt.Errorf(`ent: validator failed for field "User.Sub": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameJa(); ok {
		if err := user.NameJaValidator(v); err != nil {
			return &ValidationError{Name: "NameJa", err: fmt.Errorf(`ent: validator failed for field "User.NameJa": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GivenName(); ok {
		if err := user.GivenNameValidator(v); err != nil {
			return &ValidationError{Name: "GivenName", err: fmt.Errorf(`ent: validator failed for field "User.GivenName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FamilyName(); ok {
		if err := user.FamilyNameValidator(v); err != nil {
			return &ValidationError{Name: "FamilyName", err: fmt.Errorf(`ent: validator failed for field "User.FamilyName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locale(); ok {
		if err := user.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "Locale", err: fmt.Errorf(`ent: validator failed for field "User.Locale": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sub(); ok {
		_spec.SetField(user.FieldSub, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameJa(); ok {
		_spec.SetField(user.FieldNameJa, field.TypeString, value)
	}
	if value, ok := _u.mutation.GivenName(); ok {
		_spec.SetField(user.FieldGivenName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FamilyName(); ok {
		_spec.SetField(user.FieldFamilyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(user.FieldLocale, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetPassword sets the "Password" field.
func (_u *UserUpdateOne) SetPassword(v string) *UserUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "Password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetSub sets the "Sub" field.
func (_u *UserUpdateOne) SetSub(v string) *UserUpdateOne {
	_u.mutation.SetSub(v)
	return _u
}

// SetNillableSub sets the "Sub" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSub(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSub(*v)
	}
	return _u
}

// SetNameJa sets the "NameJa" field.
func (_u *UserUpdateOne) SetNameJa(v string) *UserUpdateOne {
	_u.mutation.SetNameJa(v)
	return _u
}

// SetNillableNameJa sets the "NameJa" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNameJa(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetNameJa(*v)
	}
	return _u
}

// SetGivenName sets the "GivenName" field.
func (_u *UserUpdateOne) SetGivenName(v string) *UserUpdateOne {
	_u.mutation.SetGivenName(v)
	return _u
}

// SetNillableGivenName sets the "GivenName" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGivenName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGivenName(*v)
	}
	return _u
}

// SetFamilyName sets the "FamilyName" field.
func (_u *UserUpdateOne) SetFamilyName(v string) *UserUpdateOne {
	_u.mutation.SetFamilyName(v)
	return _u
}

// SetNillableFamilyName sets the "FamilyName" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFamilyName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFamilyName(*v)
	}
	return _u
}

// SetLocale sets the "Locale" field.
func (_u *UserUpdateOne) SetLocale(v string) *UserUpdateOne {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "Locale" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLocale(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "Password", err: fmt.Errorf(`ent: validator failed for field "User.Password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sub(); ok {
		if err := user.SubValidator(v); err != nil {
			return &ValidationError{Name: "Sub", err: fmt.Errorf(`ent: validator failed for field "User.Sub": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameJa(); ok {
		if err := user.NameJaValidator(v); err != nil {
			return &ValidationError{Name: "NameJa", err: fmt.Errorf(`ent: validator failed for field "User.NameJa": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GivenName(); ok {
		if err := user.GivenNameValidator(v); err != nil {
			return &ValidationError{Name: "GivenName", err: fmt.Errorf(`ent: validator failed for field "User.GivenName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FamilyName(); ok {
		if err := user.FamilyNameValidator(v); err != nil {
			return &ValidationError{Name: "FamilyName", err: fmt.Errorf(`ent: validator failed for field "User.FamilyName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locale(); ok {
		if err := user.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "Locale", err: fmt.Errorf(`ent: validator failed for field "User.Locale": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sub(); ok {
		_spec.SetField(user.FieldSub, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameJa(); ok {
		_spec.SetField(user.FieldNameJa, field.TypeString, value)
	}
	if value, ok := _u.mutation.GivenName(); ok {
		_spec.SetField(user.FieldGivenName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FamilyName(); ok {
		_spec.SetField(user.FieldFamilyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(user.FieldLocale, field.TypeString, value)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
