// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dev-shimada/oidc-prac/authorization/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AccountName holds the value of the "AccountName" field.
	AccountName string `json:"AccountName,omitempty"`
	// Password holds the value of the "Password" field.
	Password string `json:"-"`
	// Sub holds the value of the "Sub" field.
	Sub string `json:"Sub,omitempty"`
	// NameJa holds the value of the "NameJa" field.
	NameJa string `json:"NameJa,omitempty"`
	// GivenName holds the value of the "GivenName" field.
	GivenName string `json:"GivenName,omitempty"`
	// FamilyName holds the value of the "FamilyName" field.
	FamilyName string `json:"FamilyName,omitempty"`
	// Locale holds the value of the "Locale" field.
	Locale       string `json:"Locale,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldAccountName, user.FieldPassword, user.FieldSub, user.FieldNameJa, user.FieldGivenName, user.FieldFamilyName, user.FieldLocale:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldAccountName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field AccountName", values[i])
			} else if value.Valid {
				_m.AccountName = value.String
			}
		case user.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case user.FieldSub:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Sub", values[i])
			} else if value.Valid {
				_m.Sub = value.String
			}
		case user.FieldNameJa:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field NameJa", values[i])
			} else if value.Valid {
				_m.NameJa = value.String
			}
		case user.FieldGivenName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field GivenName", values[i])
			} else if value.Valid {
				_m.GivenName = value.String
			}
		case user.FieldFamilyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field FamilyName", values[i])
			} else if value.Valid {
				_m.FamilyName = value.String
			}
		case user.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("AccountName=")
	builder.WriteString(_m.AccountName)
	builder.WriteString(", ")
	builder.WriteString("Password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("Sub=")
	builder.WriteString(_m.Sub)
	builder.WriteString(", ")
	builder.WriteString("NameJa=")
	builder.WriteString(_m.NameJa)
	builder.WriteString(", ")
	builder.WriteString("GivenName=")
	builder.WriteString(_m.GivenName)
	builder.WriteString(", ")
	builder.WriteString("FamilyName=")
	builder.WriteString(_m.FamilyName)
	builder.WriteString(", ")
	builder.WriteString("Locale=")
	builder.WriteString(_m.Locale)
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
