// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-shimada/oidc-prac/authorization/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetAccountName sets the "AccountName" field.
func (_c *UserCreate) SetAccountName(v string) *UserCreate {
	_c.mutation.SetAccountName(v)
	return _c
}

// SetPassword sets the "Password" field.
func (_c *UserCreate) SetPassword(v string) *UserCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetSub sets the "Sub" field.
func (_c *UserCreate) SetSub(v string) *UserCreate {
	_c.mutation.SetSub(v)
	return _c
}

// SetNameJa sets the "NameJa" field.
func (_c *UserCreate) SetNameJa(v string) *UserCreate {
	_c.mutation.SetNameJa(v)
	return _c
}

// SetGivenName sets the "GivenName" field.
func (_c *UserCreate) SetGivenName(v string) *UserCreate {
	_c.mutation.SetGivenName(v)
	return _c
}

// SetFamilyName sets the "FamilyName" field.
func (_c *UserCreate) SetFamilyName(v string) *UserCreate {
	_c.mutation.SetFamilyName(v)
	return _c
}

// SetLocale sets the "Locale" field.
func (_c *UserCreate) SetLocale(v string) *UserCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v int) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.AccountName(); !ok {
		return &ValidationError{Name: "AccountName", err: errors.New(`ent: missing required field "User.AccountName"`)}
	}
	if v, ok := _c.mutation.AccountName(); ok {
		if err := user.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "AccountName", err: fmt.Errorf(`ent: validator failed for field "User.AccountName": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "Password", err: errors.New(`ent: missing required field "User.Password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "Password", err: fmt.Errorf(`ent: validator failed for field "User.Password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sub(); !ok {
		return &ValidationError{Name: "Sub", err: errors.New(`ent: missing required field "User.Sub"`)}
	}
	if v, ok := _c.mutation.Sub(); ok {
		if err := user.SubValidator(v); err != nil {
			return &ValidationError{Name: "Sub", err: fmt.Errorf(`ent: validator failed for field "User.Sub": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameJa(); !ok {
		return &ValidationError{Name: "NameJa", err: errors.New(`ent: missing required field "User.NameJa"`)}
	}
	if v, ok := _c.mutation.NameJa(); ok {
		if err := user.NameJaValidator(v); err != nil {
			return &ValidationError{Name: "NameJa", err: fmt.Errorf(`ent: validator failed for field "User.NameJa": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GivenName(); !ok {
		return &ValidationError{Name: "GivenName", err: errors.New(`ent: missing required field "User.GivenName"`)}
	}
	if v, ok := _c.mutation.GivenName(); ok {
		if err := user.GivenNameValidator(v); err != nil {
			return &ValidationError{Name: "GivenName", err: fmt.Errorf(`ent: validator failed for field "User.GivenName": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FamilyName(); !ok {
		return &ValidationError{Name: "FamilyName", err: errors.New(`ent: missing required field "User.FamilyName"`)}
	}
	if v, ok := _c.mutation.FamilyName(); ok {
		if err := user.FamilyNameValidator(v); err != nil {
			return &ValidationError{Name: "FamilyName", err: fmt.Errorf(`ent: validator failed for field "User.FamilyName": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Locale(); !ok {
		return &ValidationError{Name: "Locale", err: errors.New(`ent: missing required field "User.Locale"`)}
	}
	if v, ok := _c.mutation.Locale(); ok {
		if err := user.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "Locale", err: fmt.Errorf(`ent: validator failed for field "User.Locale": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := user.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "User.id": %w`, err)}
		}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AccountName(); ok {
		_spec.SetField(user.FieldAccountName, field.TypeString, value)
		_node.AccountName = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.Sub(); ok {
		_spec.SetField(user.FieldSub, field.TypeString, value)
		_node.Sub = value
	}
	if value, ok := _c.mutation.NameJa(); ok {
		_spec.SetField(user.FieldNameJa, field.TypeString, value)
		_node.NameJa = value
	}
	if value, ok := _c.mutation.GivenName(); ok {
		_spec.SetField(user.FieldGivenName, field.TypeString, value)
		_node.GivenName = value
	}
	if value, ok := _c.mutation.FamilyName(); ok {
		_spec.SetField(user.FieldFamilyName, field.TypeString, value)
		_node.FamilyName = value
	}
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(user.FieldLocale, field.TypeString, value)
		_node.Locale = value
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
